### PR TITLE
Adding Variant model, migration and import task

### PR DESCRIPTION
**Pull request by ortegacmanuel**

### CODE REVIEW

**Comment by ortegacmanuel** [comment]
@acesuares Yes, I'm working on the final version of that .csv file. I'm doing it manually applying the Aruba spell-checker on the list of words of the Curacao spell-checker. Once I have it, I will commit it. Do I commit the unfinished versions?

**Comment by acesuares** [comment]
You dont' have to submit the unfinished versions, but you can if you want (and if you have other submits).

Also, maybe move the rake task to inside the migration. I don't know if that's good practice, but I do it all the time. Just move the whole Variant.rake inside the self.up part of the migration (or, call it from there, maybe?)

**Comment by ortegacmanuel** [comment]
@acesuares Working on this https://github.com/ortegacmanuel/orthography-converter in order to quickly came to a final version of the .csv file. I'm not completely happy yet with the final result but I'll keep working on it.

**Comment by acesuares** [comment]
Cool! Just include a version of the .csv then and update it if you get a better one..!

**Comment by ortegacmanuel** [comment]
@acesuares done!

**Pull request merged**
